from flask import Flask, Response, request
from flask_cors import CORS

import time
import json

app = Flask(__name__)
CORS(app, origins=["http://localhost:5173"])

streamed_events = [
	{"status": "streaming", "token": "[]", "text": "[]"},
	{"status": "streaming", "token": "I'll improve the note card and one", "text": "[]I'll improve the note card and one"},
	{"status": "streaming", "token": " action card in the second moment to better match your channel", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel"},
	{"status": "streaming", "token": "'s style and enhance the dramatic impact.", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact."},
	{"status": "streaming", "token": "<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card>", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card>"},
	{"status": "streaming", "token": "<edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>"},
	{"status": "streaming", "token": "[]", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]"},
	{"status": "streaming", "token": "I", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I"},
	{"status": "streaming", "token": "'ve enhanced both cards to better capture your signature style:\n\n1", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1"},
	{"status": "streaming", "token": ". **Note card**: Changed the text overlay to \"POV:", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV:"},
	{"status": "streaming", "token": " The Noob Has A Secret Plan \ud83d\udc80\" with", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with"},
	{"status": "streaming", "token": " dramatic zoom effect - this creates more intrigue and uses the PO", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the PO"},
	{"status": "streaming", "token": "V format that performs well in your content.\n\n2. **Action card**:", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**:"},
	{"status": "streaming", "token": " Added \"confident swagger\" and \"synchronized to music beat\" to", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to"},
	{"status": "streaming", "token": " the bed reveal moment - this emphasizes the satisf", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisf"},
	{"status": "streaming", "token": "ying music sync and character confidence that your audience loves in", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisfying music sync and character confidence that your audience loves in"},
	{"status": "streaming", "token": " these twist moments.\n\nThese improvements maintain the", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisfying music sync and character confidence that your audience loves in these twist moments.\n\nThese improvements maintain the"},
	{"status": "streaming", "token": " comedic tension while adding the polished editing", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisfying music sync and character confidence that your audience loves in these twist moments.\n\nThese improvements maintain the comedic tension while adding the polished editing"},
	{"status": "streaming", "token": " touches that make your videos so engaging.", "text": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisfying music sync and character confidence that your audience loves in these twist moments.\n\nThese improvements maintain the comedic tension while adding the polished editing touches that make your videos so engaging."},
	{"type": "final_message", "message": "[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.<edit_card>\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First \ud83d\udc80\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan \ud83d\udc80\"\n</edit_card><edit_card>\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n</edit_card>[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan \ud83d\udc80\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisfying music sync and character confidence that your audience loves in these twist moments.\n\nThese improvements maintain the comedic tension while adding the polished editing touches that make your videos so engaging."},
	{"assistantMessageId":"6e52fde4-c18d-4e70-8f48-455b6adecbd4","conversationId":"c18f617a-dff4-47a1-b5aa-8de32a736468","message":"[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.\u003cedit_card\u003e\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First 💀\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan 💀\"\n\u003c/edit_card\u003e\u003cedit_card\u003e\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n\u003c/edit_card\u003e[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan 💀\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisfying music sync and character confidence that your audience loves in these twist moments.\n\nThese improvements maintain the comedic tension while adding the polished editing touches that make your videos so engaging.","status":"complete","text":"[]I'll improve the note card and one action card in the second moment to better match your channel's style and enhance the dramatic impact.\u003cedit_card\u003e\ncardid:30aebfb2-8072-4b73-9c3f-116183ef52e1\nold_text:Text overlay: \"When The Noob Beats The Dragon First 💀\"\nnew_text:Text overlay appears with dramatic zoom: \"POV: The Noob Has A Secret Plan 💀\"\n\u003c/edit_card\u003e\u003cedit_card\u003e\ncardid:caca5ac8-effe-4380-8346-71b435ad5404\nold_text:Noob suddenly pulls out a bed from inventory\nnew_text:Noob casually pulls out a bed from inventory with confident swagger, synchronized to music beat\n\u003c/edit_card\u003e[]I've enhanced both cards to better capture your signature style:\n\n1. **Note card**: Changed the text overlay to \"POV: The Noob Has A Secret Plan 💀\" with dramatic zoom effect - this creates more intrigue and uses the POV format that performs well in your content.\n\n2. **Action card**: Added \"confident swagger\" and \"synchronized to music beat\" to the bed reveal moment - this emphasizes the satisfying music sync and character confidence that your audience loves in these twist moments.\n\nThese improvements maintain the comedic tension while adding the polished editing touches that make your videos so engaging.","type":"outline-chat","userMessageId":"6c8a87d9-2de2-4b37-917e-400dd964403b"},
]

def event_stream():
	for event in streamed_events:
		time.sleep(0.1) # 100ms delay
		yield f"data: {json.dumps(event)}\n\n"

@app.route("/stream", methods=["POST"])
def stream_response():
	if request.json.get("message") == "Hey, can you help me improve my outline?":
		return Response(event_stream(), mimetype="text/event-stream")
	else:
		return {"error": "Invalid request"}, 400

if __name__ == "__main__":
	app.run(debug=True, threaded=True)
